# Generated by Django 4.2.5 on 2023-09-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(related_name="posts", to="blog.category"),
        ),
    ]
